apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-uuid
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-uuid
  template:
    metadata:
      labels:
        app: api-uuid
    spec:
      containers:
      - name: api-uuid
        image: mateotorres2409/nodejs-uuid:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-uuid-service
  namespace: production
spec:
  selector:
    app: api-prod
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
  type: ClusterIP
